## catalog of libraries and plugins used to build the Libbulletjme project

[versions]

checkstyle = "9.3"

[libraries]

jaxb-api = "javax.xml.bind:jaxb-api:2.3.1"
junit4 = "junit:junit:4.13.2"

[bundles]

[plugins]

android-library = "com.android.library:7.4.0"
